Accounts.emailTemplates.resetPassword = {
	from: function(){
		return 'info@opz.io';
	},
	subject(user) {
		return "Reset your password on Opz.io";
	},
	text(user, url) {
		return 'Hello! Click the link below to reset your password on Meteor Todos. ${url} If you didn\'t request this email, please ignore it. Thanks, The Meteor Todos team'
	},
	html(user, url) {

		var token = url.substring(url.lastIndexOf('/') + 1, url.length);
		
		var resetURL = Meteor.absoluteUrl('reset-password/' + token);

		var title = 'Reset password';
		var subTitle = '';
		var messageTitle = 'Click <a style="color:#5ad3ce;text-decoration:none;" href="'+resetURL+'" target="_blank">here</a> to reset your password';
		var messageBody = 'Opz.io takes care of the tedious task of time tracking, providing you insights on your performance and allowing you to keep focused on your work.<br><br>(Link doesn\'t work? Copy here '+resetURL+')';
		var footer = 'You are receiving this email because you\'ve requested to reset your password on http://opz.io If you didn\'t request to restore, please ignore this email.'

		return '<body class="full-padding" style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%;">'
			+'<table class="wrapper" style="border-collapse: collapse;table-layout: fixed;min-width: 320px;width: 100%;background-color: #f5f7fa;" cellpadding="0" cellspacing="0" role="presentation"><tbody><tr><td> <div class="preheader" style="Margin: 0 auto;max-width: 560px;min-width: 280px; width: 280px;width: calc(28000% - 167440px);"> <div style="border-collapse: collapse;display: table;width: 100%;"> <div class="snippet" style="display: table-cell;Float: left;font-size: 12px;line-height: 19px;max-width: 280px;min-width: 140px; width: 140px;width: calc(14000% - 78120px);padding: 10px 0 5px 0;color: #b9b9b9;font-family: &quot;Open Sans&quot;,sans-serif;"> </div><div class="webversion" style="display: table-cell;Float: left;font-size: 12px;line-height: 19px;max-width: 280px;min-width: 139px; width: 139px;width: calc(14100% - 78680px);padding: 10px 0 5px 0;text-align: right;color: #b9b9b9;font-family: &quot;Open Sans&quot;,sans-serif;"> </div></div></div><div class="header" style="Margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);" id="emb-email-header-container"> <div class="logo emb-logo-margin-box" style="font-size: 26px;line-height: 32px;Margin-top: 6px;Margin-bottom: 20px;color: #c3ced9;font-family: Roboto,Tahoma,sans-serif;Margin-left: 20px;Margin-right: 20px;" align="center"> <div class="logo-center" style="font-size:0px !important;line-height:0 !important;" align="center" id="emb-email-header"><a style="text-decoration: none;transition: opacity 0.1s ease-in;color: #c3ced9;" href="http://opz.io" target="_blank"><img style="height: auto;width: 100%;border: 0;max-width: 160px;" src="https://opz.io/images/logo.png" alt="Opz.io" width="160"></a></div></div></div>'
				+'<div class="layout one-col fixed-width" style="Margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;"> <div class="layout__inner" style="border-collapse: collapse;display: table;width: 100%;background-color: #5ad3ce;"> <div class="column" style="text-align: left;color: #60666d;font-size: 14px;line-height: 21px;font-family: &quot;Open Sans&quot;,sans-serif;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);"> <div style="Margin-left: 20px;Margin-right: 20px;Margin-top: 24px;"> <div style="line-height:65px;font-size:1px">&nbsp;</div></div><div style="Margin-left: 20px;Margin-right: 20px;">'
					+'<h1 style="Margin-top: 0;Margin-bottom: 0;font-style: normal;font-weight: normal;color: #44a8c7;font-size: 32px;line-height: 40px;font-family: Cabin,Avenir,sans-serif;text-align: center;"><strong><span style="color:#ffffff">'+ title +'</span></strong></h1>'
					+'<h3 style="Margin-top: 20px;Margin-bottom: 12px;font-style: normal;font-weight: normal;color: #44a8c7;font-size: 17px;line-height: 26px;text-align: center;"><span style="color:#ffffff">'+ subTitle +'</span></h3>'
				+'</div><div style="Margin-left: 20px;Margin-right: 20px;"> <div style="line-height:20px;font-size:1px">&nbsp;</div></div><div style="Margin-left: 20px;Margin-right: 20px;Margin-bottom: 24px;"> <div style="line-height:12px;font-size:1px">&nbsp;</div></div></div></div></div><div class="layout one-col fixed-width" style="Margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;"> <div class="layout__inner" style="border-collapse: collapse;display: table;width: 100%;background-color: #ffffff;" emb-background-style=""> <div class="column" style="text-align: left;color: #60666d;font-size: 14px;line-height: 21px;font-family: &quot;Open Sans&quot;,sans-serif;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);"> <div style="Margin-left: 20px;Margin-right: 20px;Margin-top: 15px;Margin-bottom: 15px;"> <div style="line-height:1px;font-size:1px">&nbsp;</div></div></div></div></div>'
				+'<div class="layout fixed-width" style="Margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;"> <div class="layout__inner" style="border-collapse: collapse;display: table;width: 100%;background-color: #ffffff;" emb-background-style=""> <div class="column wide" style="text-align: left;color: #60666d;font-size: 14px;line-height: 21px;font-family: &quot;Open Sans&quot;,sans-serif;Float: left;max-width: 400px;min-width: 320px; width: 320px;width: calc(8000% - 47600px);"> <div style="Margin-left: 20px;Margin-right: 20px;Margin-top: 24px;Margin-bottom: 24px;">'
					+'<p class="size-22" style="Margin-top: 0;Margin-bottom: 0;font-size: 22px;line-height: 26px;" lang="x-size-22">'+ messageTitle +'</p>'
					+'<p style="Margin-top: 20px;Margin-bottom: 0;">'+ messageBody +'</p>'
					+'</div></div><div class="column narrow" style="text-align: left;color: #60666d;font-size: 14px;line-height: 21px;font-family: &quot;Open Sans&quot;,sans-serif;Float: left;max-width: 320px;min-width: 200px; width: 320px;width: calc(72200px - 12000%);"> <div style="font-size: 12px;font-style: normal;font-weight: normal;" align="center"> <img class="gnd-corner-image gnd-corner-image-center gnd-corner-image-top gnd-corner-image-bottom" style="border: 0;display: block;height: auto;width: 100%;max-width: 480px;" alt="" width="200" src="https://opz.io/images/bot/confused.png"> </div></div></div></div>'
					+'<div class="layout email-footer" style="Margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;"> <div class="layout__inner" style="border-collapse: collapse;display: table;width: 100%;"> <div class="column wide" style="text-align: left;font-size: 12px;line-height: 19px;color: #b9b9b9;font-family: &quot;Open Sans&quot;,sans-serif;Float: left;max-width: 400px;min-width: 320px; width: 320px;width: calc(8000% - 47600px);"> <div style="Margin-left: 20px;Margin-right: 20px;Margin-top: 10px;Margin-bottom: 10px;">'
						+'<div style="Margin-top: 20px;"> <div>Opz.io</div></div>'
						+'<div style="Margin-top: 18px;"> <div>'+ footer +'</div></div>'
					+'</div></div></div></div><div class="layout one-col email-footer" style="Margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;"> <div class="layout__inner" style="border-collapse: collapse;display: table;width: 100%;"> <div class="column" style="text-align: left;font-size: 12px;line-height: 19px;color: #b9b9b9;font-family: &quot;Open Sans&quot;,sans-serif;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);"> <div style="Margin-left: 20px;Margin-right: 20px;Margin-top: 10px;Margin-bottom: 10px;"> <div> </div></div></div></div></div><div style="line-height:40px;font-size:40px;">&nbsp;</div></td></tr></tbody></table>'
		+'</body>';
	}
};