import { Roles } from 'meteor/alanning:roles';

dbFixtures = function(){
	console.log('*** Run Fixtures')
	/* SYSTEM ROLES */
	if(Roles.getAllRoles().fetch().length < 1){ 
		console.log('SYS: Create system roles...');
		Roles.createRole('root');
		Roles.createRole('admin');
		Roles.createRole('finance');
		Roles.createRole('staff');
		Roles.createRole('guest');
	};

	if(DomainCategories.find().fetch().length === 0){ _sysInitDomainCategories(); };
	if(Domains.find().fetch().length === 0){ _sysPopulateDomains(); };
	if(DomainRules.find().fetch().length === 0){ _sysPopulateDomainRules(); };
}

_sysInitDomainCategories = function(){
	console.log('** SYS: Inserting Domain Categories....');

	var domains_categories = {
		"development": { value: 0,  label: "Development" },
		"marketing": { value: 1,  label: "Marketing" },
		"communication": { value: 2,  label: "Communication" },
		"management": { value: 3,  label: "Management" },
		"documentation": { value: 4,  label: "Documentation" },
		"settings": { value: 5,  label: "Settings" },
		"social": { value: 6,  label: "Social" },
		"leisure": { value: 7,  label: "Leisure" },
		"financial": { value: 8,  label: "Financial" },
		"shopping": { value: 9,  label: "Shopping" },
		"technical": { value: 10,  label: "Technical" },
		"travel": { value: 11,  label: "Travel" },
		"tools": { value: 12,  label: "Tools" },
		"study": { value: 13,  label: "Study" },
		"inspiration": { value: 14,  label: "Inspiration" },
		"search": { value: 15,  label: "Search" },
		"testing": { value: 16,  label: "Testing" },
		"miscelaneous": { value: 17,  label: "Miscelaneous" },
		"unknown": { value: 18,  label: "Unknown" },
	}

	_.each(domains_categories, function(values, category){
		DomainCategories.insert({
			'category': category,
			'value': values.value,
			'label': values.label,
		})
	});

	DomainCategories._ensureIndex({ "category": 1});

	console.log('** SYS: Domain Categories -- OK')

	/*
	*/
}

//List of known domains & category pairs to populate database
_sysPopulateDomains = function(){
	console.log('** SYS: Populating Domains Collection....');
	var domains_database = {
		//Search related webiste
		'yandex.com': 'search',
		'yandex.ru': 'search',
		'baidu.com': 'search',
		'ask.com': 'search',
		'answers.yahoo.com': 'search',
		'investopedia.com': 'search',
		'crunchbase.com': 'search',
		'statista.com': 'search',
		'search.yahoo.com': 'search',
		'google.com': 'search',
		'google.pt': 'search',
		'google.co.uk': 'search',
		'wikipedia.org': 'search',
		'zh-min-nan.wikipedia.org': 'search',
		'sv.wikipedia.org': 'search',
		'de.wikipedia.org': 'search',
		'fr.wikipedia.org': 'search',
		'ru.wikipedia.org': 'search',
		'it.wikipedia.org': 'search',
		'es.wikipedia.org': 'search',
		'war.wikipedia.org': 'search',
		'pl.wikipedia.org': 'search',
		'vi.wikipedia.org': 'search',
		'ja.wikipedia.org': 'search',
		'zh.wikipedia.org': 'search',
		'en.wikipedia.org': 'search',
		'pt.wikipedia.org': 'search',
		'uk.wikipedia.org': 'search',
		'ca.wikipedia.org': 'search',
		'fa.wikipedia.org': 'search',
		'no.wikipedia.org': 'search',
		'sh.wikipedia.org': 'search',
		'ar.wikipedia.org': 'search',
		'fi.wikipedia.org': 'search',
		'hu.wikipedia.org': 'search',
		'id.wikipedia.org': 'search',
		'ro.wikipedia.org': 'search',
		'cs.wikipedia.org': 'search',
		'ko.wikipedia.org': 'search',
		'sr.wikipedia.org': 'search',
		'ms.wikipedia.org': 'search',
		'tr.wikipedia.org': 'search',
		'eu.wikipedia.org': 'search',
		'eo.wikipedia.org': 'search',
		'min.wikipedia.org': 'search',
		'bg.wikipedia.org': 'search',
		'da.wikipedia.org': 'search',
		'kk.wikipedia.org': 'search',
		'sk.wikipedia.org': 'search',
		'hy.wikipedia.org': 'search',
		'he.wikipedia.org': 'search',
		'lt.wikipedia.org': 'search',
		'sl.wikipedia.org': 'search',
		'et.wikipedia.org': 'search',
		'ce.wikipedia.org': 'search',
		'gl.wikipedia.org': 'search',
		'nn.wikipedia.org': 'search',
		'uz.wikipedia.org': 'search',
		'el.wikipedia.org': 'search',
		'be.wikipedia.org': 'search',
		'th.wikipedia.org': 'search',
		'ur.wikipedia.org': 'search',
		'ka.wikipedia.org': 'search',
		'hi.wikipedia.org': 'search',
		'ta.wikipedia.org': 'search',
		'mk.wikipedia.org': 'search',
		'lv.wikipedia.org': 'search',
		'cy.wikipedia.org': 'search',
		'bs.wikipedia.org': 'search',
		'sq.wikipedia.org': 'search',
		'ht.wikipedia.org': 'search',
		'ast.wikipedia.org': 'search',
		'za-yue.wikipedia.org': 'search',
		'lb.wikipedia.org': 'search',
		'ml.wikipedia.org': 'search',
		'pnb.wikipedia.org': 'search',
		'is.wikipedia.org': 'search',
		'ga.wikipedia.org': 'search',
		'sw.wikipedia.org': 'search',
		'my.wikipedia.org': 'search',
		'pa.wikipedia.org': 'search',
		'als.wikipedia.org': 'search',
		'bar.wikipedia.org': 'search',
		'su.wikipedia.org': 'search',
		'ckb.wikipedia.org': 'search',
		'mn.wikipedia.org': 'search',
		'producthunt.com': 'search',
		'quora.com': 'search',
		'bing.com': 'search',
		//Marketing related webiste
		'analytics.twitter.com': 'marketing',
		'hubspot.com': 'marketing',
		'socialbakers.com': 'marketing',
		'hotjar.com': 'marketing',
		'mailsalad.com': 'marketing',
		'bitly.com': 'marketing',
		'app.bitly.com': 'marketing',
		'ads.twitter.com': 'marketing',
		'sendinblue.com': 'marketing',
		'hootsuite.com': 'marketing',
		'semrush.com': 'marketing',
		'tagmanager.google.com': 'marketing',
		'moz.com': 'marketing',
		'woorank.com': 'marketing',
		'link-assistant.com': 'marketing',
		'adwords.google.com': 'marketing',
		'analytics.google.com': 'marketing',
		'mailchimp.com': 'marketing',
		'admin.mailchimp.com': 'marketing',
		'business.instagram.com': 'marketing',
		'business.facebook.com': 'marketing',
		'secure.bingads.microsoft.com': 'marketing',
		'bingads.microsoft.com': 'marketing',
		'ads.bingads.microsoft.com': 'marketing',
		'business.google.com': 'marketing',
		'dashthis.com': 'marketing',
		//Communication related websites
		'sina.com.cn': 'communication',
		'mail.yahoo.com': 'communication',
		'mail.sapo.pt': 'communication',
		'outlook.office.com': 'communication',
		'hotmail.com': 'communication',
		'hangouts.google.com': 'communication',
		'office.live.com[/start/Outlook.aspx]': 'communication',
		'mail.google.com': 'communication',
		'inbox.google.com': 'communication',
		'gmail.com': 'communication',
		'slack.com': 'communication',
		'skype.com': 'communication',
		'web.skype.com': 'communication',
		'messenger.com': 'communication',
		//Management related websites
		'zoho.com': 'management',
		'zendesk.com': 'management',
		'salesforce.com': 'management',
		'rescuetime.com': 'management',
		'liquidplanner.com': 'management',
		'wunderlist.com': 'management',
		'apps.google.com': 'management',
		'office.live.com[/start/People.aspx]': 'management',
		'office.live.com[/start/Calendar.aspx]': 'management',
		'airtable.com': 'management',
		'projectplace.com': 'management',
		'asana.com': 'management',
		'app.asana.com': 'management',
		'atlassian.com': 'management',
		'atlassian.net': 'management',
		'gantt-chart.com': 'management',
		'basecamp.com': 'management',
		'contacts.google.com': 'management',
		'insightly.com': 'management',
		'googleapps.insight.ly': 'management',
		'wakatime.com': 'management',
		'favro.com': 'management',
		'trello.com': 'management',
		'toggl.com': 'management',
		'opz.io': 'management',
		'calendar.google.com': 'management',
		'keep.google.com': 'management',
		//Documentation
		'priberam.pt': 'documentation',
		'linguee.com': 'documentation',
		'sinonimos.com.br': 'documentation',
		'prezi.com': 'documentation',
		'onenote.com': 'documentation',
		'docs.com': 'documentation',
		'draw.io': 'documentation',
		'office.live.com': 'documentation',
		'portal.office.com': 'documentation',
		'office.live.com[/start/PowerPoint.aspx]': 'documentation',
		'office.live.com[/start/Excel.aspx]': 'documentation',
		'office.live.com[/start/Word.aspx]': 'documentation',
		'drive.google.com': 'documentation',
		'docs.google.com': 'documentation',
		'dropbox.com': 'documentation',
		'translate.google.com': 'documentation',
		'thesaurus.com': 'documentation',
		'translate.google.pt': 'documentation',
		'canvanizer.com': 'documentation',
		'slideshare.net': 'documentation',
		//Miscelaneous
		'maps.google.com': 'miscelaneous',
		'kickstarter.com': 'miscelaneous',
		'worldtravelawards.com': 'miscelaneous',
		//Settings
		'accounts.youtube.com': 'settings',
		'sites.google.com': 'settings',
		'admin.google.com': 'settings',
		'myaccount.google.com': 'settings',
		//Social
		'weibo.com': 'social',
		'tumblr.com': 'social',
		'twitter.com': 'social',
		'facebook.com': 'social',
		'pt-pt.facebook.com': 'social',
		'plus.google.com': 'social',
		'linkedin.com': 'social',
		'pt.linkedin.com': 'social',
		'instagram.com': 'social',
		//Leisure
		'truefootballmanager.com': 'leisure',
		'espn.com': 'leisure',
		'sports.yahoo.com': 'leisure',
		'nfl.com': 'leisure',
		'football.fantasysports.yahoo.com': 'leisure',
		'premierleague.com': 'leisure',
		'strava.com': 'leisure',
		'skysports.com': 'leisure',
		'deadspin.com': 'leisure',
		'uefa.com': 'leisure',
		'fifa.com': 'leisure',
		'football365.com': 'leisure',
		'realmadrid.com': 'leisure',
		'manutd.com': 'leisure',
		'fcbarcelona.com': 'leisure',
		'101greatgoals.com': 'leisure',
		'fourfourtwo.com': 'leisure',
		'foxsports.com': 'leisure',
		'qq.com': 'leisure',
		'sockshare.tv': 'leisure',
		'putlockerr.ac': 'leisure',
		'hdmovie14.net': 'leisure',
		'about.com': 'leisure',
		'aol.com': 'leisure',
		'msn.com': 'leisure',
		'collegehumor.com': 'leisure',
		'theonion.com': 'leisure',
		'ebaumsworld.com': 'leisure',
		'straightdope.com': 'leisure',
		'nbcsports.com': 'leisure',
		'metacafe.com': 'leisure',
		'mandatory.com': 'leisure',
		'jokes4us.com': 'leisure',
		'acidcow.com': 'leisure',
		'drodd.com': 'leisure',
		'thedailywtf.com': 'leisure',
		'boredbuttom.com': 'leisure',
		'onlinefun.com': 'leisure',
		'cracked.com': 'leisure',
		'news.google.com': 'leisure',
		'news.yahoo.com': 'leisure',
		'huffingtonpost.com': 'leisure',
		'nytimes.com': 'leisure',
		'foxnews.com': 'leisure',
		'nbcnews.com': 'leisure',
		'dailymail.co.uk': 'leisure',
		'washingtonpost.com': 'leisure',
		'wsj.com': 'leisure',
		'abcnews.go.com': 'leisure',
		'usatoday.com': 'leisure',
		'latimes.com': 'leisure',
		'weather.com': 'leisure',
		'bbc.com': 'leisure',
		'bbc.co.uk': 'leisure',
		'timesofindia.indiatimes.com': 'leisure',
		'economictimes.indiatimes.com': 'leisure',
		'marketwatch.com': 'leisure',
		'news.ycombinator.com': 'leisure',
		'cnn.com': 'leisure',
		'money.cnn.com': 'leisure',
		'motherboard.vice.com': 'leisure',
		'economist.com': 'leisure',
		'digitaltrends.com': 'leisure',
		'reuters.com': 'leisure',
		'drudgereport.com': 'leisure',
		'indianexpress.com': 'leisure',
		'fundersandfounders.com': 'leisure',
		'bloomberg.com': 'leisure',
		'cbsnews.com': 'leisure',
		'cnbc.com': 'leisure',
		'zougla.gr': 'leisure',
		'foxbusiness.com': 'leisure',
		'uk.reuters.com': 'leisure',
		'breakingnews.com': 'leisure',
		'wn.com': 'leisure',
		'independent.ie': 'leisure',
		'indymedia.org': 'leisure',
		'newswire.ca': 'leisure',
		'recode.net': 'leisure',
		'kisscartoon.me': 'leisure',
		'lifehacker.com': 'leisure',
		'entrepreneur.com': 'leisure',
		'wired.com': 'leisure',
		'commitstrip.com': 'leisure',
		'geeksaresexy.net': 'leisure',
		'theoatmeal.com': 'leisure',
		'reddit.com': 'leisure',
		'nerdist.com': 'leisure',
		'goodreads.com': 'leisure',
		'pplware.sapo.pt': 'leisure',
		'searchenginejournal.com': 'leisure',
		'buzzfeed.com': 'leisure',
		'socialmediaexaminer.com': 'leisure',
		'yahoo.com': 'leisure',
		'sicmulhers.apo.pt': 'leisure',
		'giphy.com': 'leisure',
		'dinheirovivo.pt': 'leisure',
		'techcrunch.com': 'leisure',
		'forbes.com': 'leisure',
		'zdnet.com': 'leisure',
		'meetup.com': 'leisure',
		'sysads.co.uk': 'leisure',
		'theregister.co.uk': 'leisure',
		'howtogeek.com': 'leisure',
		'sulinformacao.pt': 'leisure',
		'theguardian.com': 'leisure',
		'zerozero.pt': 'leisure',
		'sapo.pt': 'leisure',
		'economico.sapo.pt': 'leisure',
		'sicnoticias.sapo.pt': 'leisure',
		'lequipe.fr': 'leisure',
		'searchenginewatch.com': 'leisure',
		'tnooz.com': 'leisure',
		'record.xl.pt': 'leisure',
		'thenextweb.com': 'leisure',
		'play.spotify.com': 'leisure',
		'p3.publico.pt': 'leisure',
		'vice.com': 'leisure',
		'feedly.com': 'leisure',
		'rtp.pt': 'leisure',
		'uefa.com': 'leisure',
		'netflix.com': 'leisure',
		'dice.com': 'leisure',
		'eventbrite.com': 'leisure',
		'abola.pt': 'leisure',
		'io9.gizmodo.com': 'leisure',
		'viralthread.com': 'leisure',
		'jn.pt': 'leisure',
		'publico.pt': 'leisure',
		'venturebeat.com': 'leisure',
		'observador.pt': 'leisure',
		'vimeo.com': 'leisure',
		'serverfault.com': 'leisure',
		'heroku.com': 'leisure',
		'dashboard.heroku.com': 'leisure',
		'devcenter.heroku.com': 'leisure',
		'blog.heroku.com': 'leisure',
		'pinterest.com': 'leisure',
		'pt.pinterest.com': 'leisure',
		'es.pinterest.com': 'leisure',
		'thenextweb.com': 'leisure',
		'9gag.com': 'leisure',
		'9gag.tv': 'leisure',
		'youtube.com': 'leisure',
		'soundcloud.com': 'leisure',
		'twitch.tv': 'leisure',
		'medium.com': 'leisure',
		'imdb.com': 'leisure',
		'theverge.com': 'leisure',
		'boredpanda.com': 'leisure',
		'smashingmagazine.com': 'leisure',
		'tabonito.pt': 'leisure',
		//Financial	
		'caixaebankingonline.cgd.pt': 'financial',
		'app.invoicexpress.com': 'financial',
		'bpinet.pt': 'financial',
		'mbnet.pt': 'financial',
		'cgd.pt': 'financial',
		'paypal.com': 'financial',
		//Shopping
		'taobao.com': 'shopping',
		'custojusto.pt': 'shopping',
		'kuantokusta.pt': 'shopping',
		'codecanyon.net': 'shopping',
		'fnac.pt': 'shopping',
		'pcdiga.com': 'shopping',
		'pt.aliexpress.com': 'shopping',
		'amazon.com': 'shopping',
		'amazon.co.uk': 'shopping',
		'ebay.com': 'shopping',
		'ebay.co.uk': 'shopping',
		'ebay.es': 'shopping',
		'olx.pt': 'shopping',
		'jumbo.pt': 'shopping',
		//Technical
		'sourceforge.net': 'technical',
		'developer.apple.com': 'technical',
		'compose.io': 'technical',
		'tensorflow.org': 'technical',
		'materializecss.com': 'technical',
		'pythonanywhere.com': 'technical',
		'docs.aws.amazon.com': 'technical',
		'chartjs.org': 'technical',
		'plugins.jquery.com': 'technical',
		'ionic.io': 'technical',
		'phonegap.com': 'technical',
		'eclipse.org': 'technical',
		'instagram.com[/developer/]': 'technical',
		'learningjquery.com': 'technical',
		'xamarin.com': 'technical',
		'developer.xamarin.com': 'technical',
		'electron.atom.io': 'technical',
		'technet.microsoft.com': 'technical',
		'insights.ubuntu.com': 'technical',
		'windows.microsoft.com': 'technical',
		'docs.oracle.com': 'technical',
		'code.visualstudio.com': 'technical',
		'jetbrains.com': 'technical',
		'developer.android.com': 'technical',
		'docs.mongodb.org': 'technical',
		'atmospherejs.com': 'technical',
		'forums.meteor.com': 'technical',
		'modulus.io': 'technical',
		'my.modulus.io': 'technical',
		'html5doctor.com': 'technical',
		'maps.googleapis.com': 'technical',
		'developer.vimeo.com': 'technical',
		'help.bingads.microsoft.com': 'technical',
		'postgresonline.com': 'technical',
		'modernizr.com': 'technical',
		'sugarcrm.com': 'technical',
		'golang.org': 'technical',
		'nodejs.org': 'technical',
		'docs.npmjs.com': 'technical',
		'npmjs.com': 'technical',
		'godaddy.com': 'technical',
		'd3js.org': 'technical',
		'postgresql.org': 'technical',
		'fullcalendar.io': 'technical',
		'compass-style.org': 'technical',
		'console.developers.google.com': 'technical',
		'facebook.github.io': 'technical',
		'guide.meteor.com': 'technical',
		'docs.meteor.com': 'technical',
		'meteor.com': 'technical',
		'visjs.org': 'technical',
		'momentjs.com': 'technical',
		'getbootstrap.com': 'technical',
		'rackspace.com': 'technical',
		'wiki.python.org': 'technical',
		'linux.com': 'technical',
		'developer.chrome.com': 'technical',
		'developer.mozilla.org': 'technical',
		'dev.mysql.com': 'technical',
		'docker.com': 'technical',
		'whois.net': 'technical',
		'newrelic.com': 'technical',
		'bitbucket.org': 'technical',
		'php.net': 'technical',
		'foundation.zurb.com': 'technical',
		'cloudflare.com': 'technical',
		'aws.amazon.com': 'technical',
		'ubuntuforums.org': 'technical',
		'help.ubuntu.com': 'technical',
		'jsfiddle.net': 'technical',
		'masonry.desandro.com': 'technical',
		'djangosnippets.org': 'technical',
		'stackstorm.com': 'technical',
		'security.stackexchange.com': 'technical',
		'stackexchange.com': 'technical',
		'stripe.com': 'technical',
		'github.com': 'technical',
		'help.github.com': 'technical',
		'sendgrid.com': 'technical',
		'app.sendgrid.com': 'technical',
		'mailtrap.io': 'technical',
		'python.org': 'technical',
		'stackoverflow.com': 'technical',
		'developers.google.com': 'technical',
		'developers.facebook.com': 'technical',
		'backbonejs.org': 'technical',
		'askubuntu.com': 'technical',
		'w3schools.com': 'technical',
		'velocityjs.org': 'technical',
		'digitalocean.com': 'technical',
		'cloud.digitalocean.com': 'technical',
		'developer.paypal.com': 'technical',
		'css-tricks.com': 'technical',
		'support.google.com': 'technical',
		'djangoproject.com': 'technical',
		'sandbox.paypal.com': 'technical',
		'stackshare.io': 'technical',
		'docs.getsentry.com': 'technical',
		'msdn.microsoft.com': 'technical',
		'social.msdn.microsoft.com': 'technical',
		'html5rocks.com': 'technical',
		'docs.python.org': 'technical',
		'docs.python-guide.org': 'technical',
		'fontawesome.io': 'technical',
		'jquery.com': 'technical',
		'api.jquery.com': 'technical',
		'rubygems.org': 'technical',
		'docs.celeryproject.org': 'technical',
		'reactjs.net': 'technical',
		'realpython.com': 'technical',
		//Travel
		'tripadvisor.com': 'travel',
		'expedia.com': 'travel',
		'ryanair.com': 'travel',
		'easyjet.com': 'travel',
		'flytap.com': 'travel',
		'airbnb.com': 'travel',
		'momondo.pt': 'travel',
		'booking.com': 'travel',
		'hotels.com': 'travel',
		'zomato.com': 'travel',
		'delta.com': 'travel',
		'uber.com': 'travel',
		//Tools
		'mediafire.com': 'tools',
		'xe.com': 'tools',
		'tinyurl.com': 'tools',
		'unminify.com': 'tools',
		'placehold.it': 'tools',
		'hashtagify.me': 'tools',
		'datavalidation.com': 'tools',
		'epochconverter.com': 'tools',
		'robomongo.org': 'tools',
		'sublimetext.com': 'tools',
		'kadira.io': 'tools',
		'css3maker.com': 'tools',
		'caniuse.com': 'tools',
		'html-ipsum.com': 'tools',
		'tawk.to': 'tools',
		'dochub.com': 'tools',
		'ifttt.com': 'tools',
		'zapier.com': 'tools',
		'office.live.com/start/OneDrive.aspx': 'tools',
		'code.runnable.com': 'tools',
		'wetransfer.com': 'tools',
		'javascript-minifier.com': 'tools',
		'cssminifier.com': 'tools',
		'pastebin.com': 'tools',
		'wordpress.org': 'tools',
		'wix.com': 'tools',
		'ckeditor.com': 'tools',
		'disqus.com': 'tools',
		//Study
		'codecademy.com': 'study',
		'coursera.org': 'study',
		'udemy.com': 'study',
		'tutorialize.me': 'study',
		'sitepoint.com': 'study',
		'learn.jquery.com': 'study',
		'tutorialspoint.com': 'study',
		//Inspiration/design
		'dribbble.com': 'inspiration',
		'fontsgeek.com': 'inspiration',
		'creative.adobe.com': 'inspiration',
		'flaticon.com': 'inspiration',
		'moqups.com': 'inspiration',
		'canva.com': 'inspiration',
		'snazzymaps.com': 'inspiration',
		'500px.com': 'inspiration',
		'flickr.com': 'inspiration',
		'fonts.google.com': 'inspiration',
		'typekit.com': 'inspiration',
		'coolors.co': 'inspiration',
		'awwwards.com': 'inspiration',
		'wrapbootstrap.com': 'inspiration',
		'themeforest.net': 'inspiration',
		'behance.net': 'inspiration',
		'codepen.io': 'inspiration',
		'tympanus.net': 'inspiration',
		'deviantart.com': 'inspiration',
		//Development
		'editor.wix.com': 'development',
		'localhost': 'development',
		'127.0.0.1:8888': 'development',
		'localhost:8888': 'development',
		'127.0.0.1:8000': 'development',
		'localhost:8000': 'development',
		'127.0.0.1:3000': 'development',
		'localhost:3000': 'development',
		//Testing
		'speedtest.net': 'testing',
		'webpagetest.org': 'testing',
		'websitetest.com': 'testing',
		'nibbler.silktide.com': 'testing',
		'tools.pingdom.com': 'testing',
		'gtmetrix.com': 'testing',
		'testmysite.thinkwithgoogle.com': 'testing',
		'loadimpact.com': 'testing',
		'crossbrowsertesting.com': 'testing',
		'browserstack.com': 'testing',
		'browserling.com': 'testing',
	}

	_.each(domains_database, function(category, domain){
		var categoryId = DomainCategories.findOne({ category: category })._id;

		Domains.insert({
			'domain': domain,
			'category': categoryId,
		});
	});

	Domains._ensureIndex({ "domain": 1});

	console.log('** SYS: Populating Domains -- OK');
}

//The default rules when an organization is created
_sysPopulateDomainRules = function(){
	console.log('** SYS: Populating Domain Rules....');

	//0 = Sunday
	//1 = Monday
	//....
	//7 = Saturday
	var default_private_days = [0, 7];
	var default_private_hours = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 19, 20, 21, 22, 23];

	var domains = Domains.find().fetch();
	var users = Meteor.users.find().fetch();
	var private = true;


	_.each(domains, function(domain, key){
		var category = DomainCategories.findOne({_id: domain.category });
		console.log(category)
		_.each(users, function(user, k){
			var domainRule = _createDefaultUserDomainRule(user, domain, category)
			
			DomainRules.insert(domainRule);

		});
	});

	console.log('** SYS: Populating Domain Rules -- OK');
};